let products = [
    {
        id:101,
        subject:"Math Lesson",
        location: "Oxford",
        price: 80,
        image: "images/maths.png",
        availableInventory: 5,
        rating:5,
        quantity:0,
        category: 'Maths',
        grade:'10'
    },
    {
        id:102,
        subject:"English Lesson",
        location: "Oxford",
        price: 80,
        image: "images/english.png",
        availableInventory: 6,
        rating:3,
        quantity:0,
        category: 'English',
        grade:'12'
    },
    {
        id:103,
        subject:"Accounting Lesson",
        location: "Cardiff",
        price: 100,
        image: "images/accounting.png",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Accounting',
        grade:'11'
    },
    {
        id:104,
        subject:"Accounting Lesson",
        location: "London",
        price: 200,
        image: "images/accounting2.png",
        availableInventory: 8,
        rating:5,
        quantity:0,
        category: 'Accounting',
        grade:'11'
    },
    {
        id:105,
        subject:"English Lesson",
        location: "Cambridge",
        price: 120,
        image: "images/english2.png",
        availableInventory: 5,
        rating:2,
        quantity:0,
        category: 'English',
        grade:'12'
    },
    {
        id:106,
        subject:"Math Lesson",
        location: "London",
        price: 100,
        image: "images/maths.gif",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Maths',
        grade:'13'
    },
    {
        id:107,
        subject:"French Lesson",
        location: "Cambridge",
        price: 80,
        image: "images/french.png",
        availableInventory: 5,
        rating:2,
        quantity:0,
        category: 'French',
        grade:'13'
    },
    {
        id:108,
        subject:"French Lesson",
        location: "Oxford",
        price: 150,
        image: "images/french2.png",
        availableInventory: 5,
        rating:5,
        quantity:0,
        category: 'French',
        grade:'11'
    },
    {
        id:109,
        subject:"History Lesson",
        location: "London",
        price: 90,
        image: "images/history.png",
        availableInventory: 5,
        rating:1,
        quantity:0,
        category: 'History',
        grade:'12'
    },
    {
        id:110,
        subject:"History Lesson",
        location: "York",
        price: 135,
        image: "images/history2.png",
        availableInventory: 5,
        rating:1,
        quantity:0,
        category: 'History',
        grade:'13'
    },
    {
        id:111,
        subject:"Literature Lesson",
        location: "Birmingham",
        price: 150,
        image: "images/literature.png",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Literature',
        grade:'11'
    },
    {
        id:112,
        subject:"Literature Lesson",
        location: "York",
        price: 90,
        image: "images/literature.gif",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Literature',
        grade:'13'
    },
    {
        id:113,
        subject:"Music Lesson",
        location: "Manchester",
        price: 200,
        image: "images/Music.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Music',
        grade:'13'
    },
    {
        id:114,
        subject:"Music Lesson",
        location: "London",
        price: 115,
        image: "images/Music2.gif",
        availableInventory: 5,
        rating:5,
        quantity:0,
        category: 'Music',
        grade:'11'
    },
    {
        id:115,
        subject:"Music Lesson",
        location: "Liverpool",
        price: 70,
        image: "images/Music.gif",
        availableInventory: 6,
        rating:1,
        quantity:0,
        category: 'Music',
        grade:'10'
    },
    {
        id:116,
        subject:"Physics Lesson",
        location: "London",
        price: 75,
        image: "images/physics.gif",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Physics',
        grade:'10'
    },
    {
        id:117,
        subject:"Physics Lesson",
        location: "Nottingham",
        price: 150,
        image: "images/physics.gif",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Physics',
        grade:'13'
    },
    {
        id:118,
        subject:"Physics Lesson",
        location: "Liverpool",
        price: 90,
        image: "images/physics.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Physics',
        grade:'11'
    },
    {
        id:119,
        subject:"Spanish Lesson",
        location: "Birmingham",
        price: 90,
        image: "images/spanish.png",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Spanish',
        grade:'12'
    },
    {
        id:120,
        subject:"Geography Lesson",
        location: "Nottingham ",
        price: 105,
        image: "images/geography.gif",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Geography',
        grade:'10'
    },
    {
        id:121,
        subject:"Geography Lesson",
        location: "London",
        price: 159,
        image: "images/geography.gif",
        availableInventory: 5,
        rating:5,
        quantity:0,
        category: 'Geography',
        grade:'13'
    },
    {
        id:122,
        subject:"Geography Lesson",
        location: "Manchester",
        price: 90,
        image: "images/geography.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Geography',
        grade:'12'
    },
    {
        id:123,
        subject:"Economics Lesson",
        location: "Cardiff",
        price: 120,
        image: "images/economics.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Economics',
        grade:'10'
    },
    {
        id:124,
        subject:"Economics Lesson",
        location: "Londons",
        price: 90,
        image: "images/economics2.png",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Economics',
        grade:'12'
    },
    {
        id:125,
        subject:"Computer Science Lesson",
        location: "London",
        price: 100,
        image: "images/computer.png",
        availableInventory: 5,
        rating: 2,
        quantity:0,
        category: 'Computer Science',
        grade:'13'
    },
    {
        id:126,
        subject:"Computer Science Lesson",
        location: "Manchester",
        price: 200,
        image: "images/computer2.png",
        availableInventory: 5,
        rating: 5,
        quantity:0,
        category: 'Computer Science',
        grade:'12'
    },
    {
        id:127,
        subject:"Chemistry Lesson",
        location: "London",
        price: 100,
        image: "images/chemistry.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Chemistry',
        grade:'10'
    },
    {
        id:128,
        subject:"Chemistry Lesson",
        location: "Nottingham",
        price: 80,
        image: "images/chemistry.gif",
        availableInventory: 5,
        rating: 3,
        quantity:0,
        category: 'Chemistry',
        grade:'11'
    },
    {
        id:129,
        subject:"Biology Lesson",
        location: "London",
        price: 99,
        image: "images/Biology.png",
        availableInventory: 5,
        rating:3,
        quantity:0,
        category: 'Biology',
        grade:'10'
    },
    {
        id:130,
        subject:"Biology Lesson",
        location: "Nottingham",
        price: 87,
        image: "images/Biology.gif",
        availableInventory: 5,
        rating: 4,
        quantity:0,
        category: 'Biology',
        grade:'13'
    },
    {
        id:131,
        subject:"Art and Design Lesson",
        location: "York",
        price: 101,
        image: "images/Art.gif",
        availableInventory: 5,
        rating:4,
        quantity:0,
        category: 'Art and Design',
        grade:'12'
    },
    {
        id:132,
        subject:"Art and Design Lesson",
        location: "Birmingham",
        price: 140,
        image: "images/Art.png",
        availableInventory: 5,
        rating:2,
        quantity:0,
        category: 'Art and Design',
        grade:'10'
    },
]
